### ISSUE TITLE
Missing speed stat icon and ship type icons

### ISSUE THREAD

**Issue by ZikiHero** [Fernando2603/AzurLane#37]
There is a missing speed stat icon. Also ship type IXm IXv IXs icons.

**Comment by Fernando2603** [comment]
Stats and hulltype icon assets are old asset and manually uploaded, but i will add the auto update on it later, maybe after lunar new year, probably 1 or 2 week.

**Comment by Fernando2603** [comment]
Now for stats you can use `images/attribute`, for `images/stats` will removed in **2025**.
also added [attribute.json](https://github.com/Fernando2603/AzurLane/blob/main/attribute.json), it come with 5 icon variant.
- icon: contains raw png image extracted from game
- iconbox: same as raw png image but with 1:1 ratio by adding padding
- icon128: 128x128 pixel image, resized from iconbox with LANZCOS method.
- icon64: same as icon128 but in 64x64 size
- icon32: same as icon128 but in 32x32 size

For `images/type` is overhauled, old file are removed, [hulltype.json](https://github.com/Fernando2603/AzurLane/blob/main/hulltype.json) also changed. Below are new structure for hulltype.
```Typescript
type Link = string | null;

const LABEL_LIST = [
  "AE", "AR", "BB", "BBV", "BC", "BM",
  "CA", "CB", "CL", "CV", "CVL", "DD", "DDG",
  "IX", "IXM", "IXS", "IXV", "SS", "SSV",
  "BB/BC", "CA/CB", "CL/DD", "CV/CVL", "SS/SSV"
];

type Hulltype = {
  id: number;
  name: string;
  short: string;
  position: string
  icon: Link;
  tech: Link; // text/icon used in fleet tech page
  title: Link; // text/icon used in ship profile
  label: {
    [label_name: string]: Link; // used by gear
  };
};

type HulltypeData = {
  [hulltype_id: string]: Hulltype;
};
```
Here some icon sample:
![](https://raw.githubusercontent.com/Fernando2603/AzurLane/main/images/type/1.png) ![](https://raw.githubusercontent.com/Fernando2603/AzurLane/main/images/type/tech_1.png) ![](https://raw.githubusercontent.com/Fernando2603/AzurLane/main/images/type/title_1.png)
![](https://raw.githubusercontent.com/Fernando2603/AzurLane/main/images/type/label_1.png)
![](https://raw.githubusercontent.com/Fernando2603/AzurLane/main/images/type/label_55.png)

you can read more in [CHANGELOG.md](https://github.com/Fernando2603/AzurLane/blob/main/docs/CHANGELOG.md), thanks for opening this issue, don't hesitate to opening another issue if you have something to ask or some found some missing asset or wanna request some new asset.
