### ISSUE TITLE
Missing skill icons

### ISSUE THREAD

**Issue by ZikiHero** [Fernando2603/AzurLane#38]
Could you please add missing skill images?

Here is the list:
`[1001, 1002, 1004, 1005, 1011, 1013, 1031, 1032, 1034, 1042, 1051, 1052, 1061, 1081, 1091, 2001, 2011, 2021, 2031, 2041, 2051, 2061, 2071, 2081, 2091, 2101, 2121, 2131, 2141, 2151, 2161, 2171, 2181, 2191, 2201, 3001, 3011, 3021, 3031, 3041, 3051, 3511, 3521, 3531, 3571, 3581, 3591, 3611, 3621, 3631, 4011, 4021, 4041, 4051, 4071, 4081, 4091, 4101, 4111, 4121, 4131, 4141, 4151, 4161, 4181, 5001, 5021, 5031, 5041, 5051, 5061, 5071, 5081, 5101, 5111, 6411, 6415, 6550, 9050, 9061, 9071, 9081, 9090, 9101, 9110, 9711, 10521, 10522, 14890, 15210, 15220, 16430, 17560, 19001, 19002, 19370, 20011, 20012, 20021, 20022, 20031, 20032, 20041, 20042, 20051, 20052, 20061, 20062, 20081, 20082, 20091, 20092, 20111, 20112, 20121, 20122, 20131, 20132, 20133, 20141, 20142, 20211, 20212, 20221, 20222, 20231, 20232, 20241, 20242, 20251, 20252, 20261, 20262, 20281, 20282, 20311, 20312, 20321, 20322, 21011, 21012, 21016, 21017, 21021, 21022, 21026, 21027, 21031, 21032, 21041, 21042, 21051, 21052, 21061, 21062, 21071, 21072, 21081, 21082, 21091, 21092, 21111, 21112, 21121, 21122, 21131, 21132, 21141, 21142, 21151, 21152, 21161, 21162, 21171, 21172, 21181, 21182, 21191, 21192, 21211, 21212, 21221, 21222, 21231, 21232, 21241, 21242, 22011, 22012, 22021, 22022, 22031, 22032, 22041, 22042, 22051, 22052, 22056, 22057, 22061, 22062, 22071, 22072, 22081, 22082, 22091, 22092, 22131, 22132, 22141, 22142, 22151, 22152, 22161, 22162, 22211, 22212, 22221, 22222, 22231, 22232, 22241, 22242, 22251, 22252, 22253, 22254, 22255, 22261, 22262, 22311, 22312, 22411, 22412, 23011, 23012, 23021, 23022, 23031, 23032, 23041, 23042, 23051, 23052, 23111, 23112, 23121, 23122, 23131, 23132, 23211, 23212, 23221, 23222, 23231, 23232, 23241, 23242, 23311, 23312, 23321, 23322, 23411, 23412, 23511, 23512, 24011, 24012, 24031, 24032, 24041, 24042, 24061, 24062, 24111, 24112, 24121, 24122, 24131, 24132, 24141, 24142, 24151, 24152, 25011, 25012, 25021, 25022, 25031, 25032, 25041, 25042, 25211, 25212, 25213, 25214, 25221, 25222, 25231, 25232, 25511, 25512, 26011, 26012, 26021, 26022, 26031, 26032, 26111, 26112, 26211, 26212, 26311, 26312, 28011, 28012, 28021, 28022, 28031, 28032, 28111, 28112, 28121, 28122, 28211, 28212, 28221, 28222, 29021, 29022, 29051, 29052, 29061, 29062, 29081, 29082, 29091, 29092, 29101, 29102, 29111, 29112, 29121, 29122, 29123, 29131, 29132, 29141, 29142, 29171, 29172, 29191, 29192, 29201, 29202, 29211, 29212, 29221, 29222, 29231, 29232, 29241, 29242, 29251, 29252, 29261, 29262, 29271, 29272, 29281, 29282, 29311, 29312, 29321, 29322, 29331, 29332, 29341, 29342, 29351, 29361, 29362, 29371, 29372, 29381, 29382, 29391, 29392, 29401, 29402, 29411, 29412, 29421, 29422, 29431, 29432, 29441, 29442, 29451, 29452, 29461, 29462, 29471, 29472, 29481, 29482, 29491, 29492, 29501, 29502, 29511, 29512, 29521, 29531, 29541, 29542, 29551, 29552, 29561, 29562, 29571, 29572, 29581, 29582, 29591, 29592, 29601, 29602, 29611, 29612, 29621, 29622, 29631, 29632, 29641, 29642, 29651, 29652, 29661, 29662, 29671, 29672, 29681, 29682, 29691, 29692, 29701, 29702, 29711, 29712, 29721, 29722, 29731, 29732, 29741, 29742, 29751, 29752, 29761, 29762, 29771, 29772, 29781, 29782, 29791, 29792, 29801, 29802, 29811, 29812, 29821, 29822, 29831, 29832, 29841, 29842, 29851, 29852, 29861, 29862, 29881, 29882, 29891, 29892, 29901, 29902, 29911, 29912, 29921, 29922, 29931, 29932, 29941, 29942, 29951, 29952, 29961, 29962, 29971, 29972, 29981, 29982, 29991, 29992, 30001, 30011, 30021, 30022, 30031, 30032, 30041, 30051, 30061, 30062, 30071, 30072, 30081, 30082, 30091, 30092, 30101, 30102, 30111, 30112, 30121, 30122, 30131, 30132, 30141, 30142, 30151, 30152, 30161, 30162, 30171, 30172, 30181, 30182, 30191, 30192, 800071, 800072, 800081, 800082, 800121, 800122, 800161, 800162, 800201, 800202, 800251, 800252, 800291, 800292, 800331, 800332, 800371, 800372, 800411, 800412, 800451, 800452, 800491, 800492, 800531, 800532, 800571, 800572, 800601, 800602, 800631, 800632, 800671, 800672, 800701, 800702, 800741, 800742, 800771, 800772, 800811, 800812, 800841, 800842, 800881, 800882, 800911, 800912, 800951, 800952, 800981, 800982, 801011, 801012, 801051, 801052, 801081, 801082]`

I made this list as a difference between image names in `images/skills` folder and skill ids in [AzurLaneData - ship_data_template.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/EN/sharecfgdata/ship_data_template.json) in "buff_list" list.

**Comment by Fernando2603** [comment]
I see what you're doing here. There's a bit of misunderstanding about how these assets work or how to use this repository. You can't directly compare `images/skills` with buff ids. Instead, you need to retrieve the icon from `buffCfg.json` or simply use my [skill.json](https://github.com/Fernando2603/AzurLane/blob/main/skill.json) or [skill_icon.json](https://github.com/Fernando2603/AzurLane/blob/main/skill_icon.json) which is the intended way that can be accessed buff id or skill id like what you needed.

I'm aware that some skills are not included due to reasons I can't explain at the moment (I don't have access to my computer right now), such as non-existent ship skills, enemy skills, equip skill, etc.

However, I believe the current skill assets cover the entire range of ship skills and hidden skills as well.

But i can be wrong, i will keep this issue open and investigate this later when i have access to my computer.

**Comment by ZikiHero** [comment]
Yeah, you are probably right. There might be multiple skills with the same icon but different IDs (different buff), and I was assuming that each skill has a unique icon. I'll check that tomorrow, and if all icons load correctly, I'll close the issue. Thanks for clarifying.

**Comment by ZikiHero** [comment]
I've double-checked the skill icon IDs and data in `buffCfg.json`. It appears that the following IDs are missing: `[9050, 9061, 9070, 9080, 9090, 9100, 9110, 9711]`. However, they are assigned to ship IDs that currently do not have a corresponding name, indicating they may be for future skills. I will close the issue. Thanks for clarifying my misunderstanding.
