### ISSUE TITLE
Migration to python?

### ISSUE THREAD

**Issue by iSMP14** [Fernando2603/AzurLane#39]
Have you considered migrating this API to Python?

**Comment by Fernando2603** [comment]
I'm not quite sure what you mean "migrating", maybe creating python wrapper package similiar to [azurapi-py](https://github.com/AzurAPI/azurapi-py)?, if that the case my answer is "**I haven't considered it yet**".

Currently, the JSON based API work well across most programming languages, so creating wrapper package isn't my primary focus in this project.

Another reason I haven't created a wrapper package is that I'm not the best at designing something that needs frequent updates on the user end. Instead, I provide the JSON data in the GitHub repository and let developers decide how to handle its delivery and updates locally.

**Comment by iSMP14** [comment]
Okay! Amazing work btw

**Comment by Fernando2603** [comment]
Thanks
