### ISSUE TITLE
Guide to using sparse-checkout

### ISSUE THREAD

**Issue by azurstarshine** [Fernando2603/AzurLane#40]
I've been working a little with this repo, and I've been delving into using [git's sparse-checkout feature](https://git-scm.com/docs/git-sparse-checkout) in combination with `--filter` to only download the files I'm actually interested in. This keeps the repository much smaller on my disk and avoids downloading gigabytes of data I'm not interested in.

Would you be interested in a pull request adding a short guide about using it to the README? Users save bandwidth and data and get the ability to download only changes without having to write their own code. I also suspect Github would be much happier with people using built in git features than manually sending web requests for raw file downloads.

I understand that this might be more "advanced" usage, but I've found it extremely useful.

**Comment by Fernando2603** [comment]
That’s actually a great idea, tbh. I hadn’t thought about it before. I’d totally be up for a pull request if you want to add that! Otherwise, I’ll try to research it later, but honestly, I haven’t had much time for this project, so it might take me a while to put a guide together myself.

Thanks for suggesting this!

**Comment by azurstarshine** [comment]
@Fernando2603 I've got a draft written up [here](https://github.com/azurstarshine/AzurLaneENResources/tree/sparse-instructions?tab=readme-ov-file#sparse-checkout-with-git). Feel free to look it over.

I have a question before I submit a pull request, though. I wrote it directly into the README, but would you prefer it be over inside the docs directory? Either one is fine with me. Just trying to think about the most appropriate place for it.

**Comment by Fernando2603** [comment]
I think it’s better to keep them separate, as the README is generated server-side after every change to track the repo size. You can edit the README to include minimal information with a link to the docs, and I’ll handle passing it to the backend later.

It looks good to me overall. Also, don’t forget to include some credits for yourself.

**Comment by azurstarshine** [comment]
My name will be on the commits and listed as a contributor. That's enough credit for me.

**Comment by Fernando2603** [comment]
Thank you so much for contribution. 👍
